netty100:
  redisson:
    single:
      enable: true
      config:
        address: redis://60.204.147.221:6379
        password: rediszqCEuDLy5P6dZk1eKxZH4vhOW6B
        database: 15
spring:
  datasource:
    url: jdbc:mysql://60.204.147.221/netty100?useUnicode=true&amp&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMutiQueries=true&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true&useOldAliasMetadataBehavior=true
    username: root
    password: a6tO0fB20sTZlZev
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      auto-commit: false
      pool-name: HikariCP
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: whyjob-qa@ienglish.cn
    password: 75eNfDbjrqFVNh8w
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
  cloud:
    sentinel:
      log:
        dir: /tmp
      transport:
        port: 8722
        dashboard: sentinel-dashboard:8090
      enabled: true
      filter:
        enabled: true
swagger:
  enable: true
server:
  port: 8090
ding-talk:
  secret: SECdc8b2b87f0fdff6cea08829f3bb0219b67ac8ce1fd22a29ba17ca8ecb5cb7cb1
  token: 646dfd4ae6580743fd1e64fc62fd6a07c92d51eba54fc24934352fe2903cfc4d           